import Head from "next/head";
import styles from "./index.module.sass";
import { useEffect } from "react";
import AOS from "aos";
import axios from "axios";

// COMPONENT
import Navbar from "../components/navbar";
import SocialLists from "../components/social-lists";
import Hero from "../components/hero";
import About from "../components/about";
import Education from "../components/education";
import Portfolio from "../components/portfolio";
import ModeSettings from "../components/mode-settings";

export default function App(props) {
  useEffect(() => {
    AOS.init({ duration: 3000 });
    window.addEventListener("load", AOS.refresh);
    window.addEventListener("scroll", () => {
      AOS.refresh();
    });
  }, []);

  return (
    <>
      {/* Website Head Paet And Meta Tags Container */}
      <Head>
        <title>Moustapha Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Actual Page Components Wrapper Area */}
      {props.projects && (
        <>
          <SocialLists data={props.links} />
          <ModeSettings />
          <main id="app-main" className={styles.container}>
            <div className="row g-0">
              <div className="offset-1 col-10">
                <Navbar data={props.sections} />
                <Hero data={props.info} />
                <About data={props.about} />
                <Education data={props.education} />
                <Portfolio data={props.projects} />
              </div>
            </div>
          </main>
        </>
      )}
    </>
  );
}

export async function getServerSideProps() {
  const res = await axios.get("http://localhost:3000/api/data");
  return {
    props: res.data,
  };
}
